server:
  port: 9001


spring:
  application:
    name: nacos-provider-payment
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #nacos地址

 # nacos 管理界面
management:
  endpoints:
    web:
      exposure:
        include=*: