server:
  port: 8001

spring:
  application:
    name: provider-paymment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/my?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml    # mapper文件路径
  type-aliases-package: com.xiaoxu.api.entities    # 所有Entity别名类所在包